#!/bin/bash

# Production Environment Variables Setup Script
# This script helps you set up all required environment variables in Vercel

echo "🚀 Production Environment Variables Setup Guide"
echo "================================================"
echo ""

echo "📋 CRITICAL ENVIRONMENT VARIABLES REQUIRED"
echo "=========================================="
echo ""

echo "🔐 1. AUTHENTICATION (CLERK)"
echo "   - CLERK_PUBLISHABLE_KEY=pk_live_YOUR_PRODUCTION_KEY"
echo "   - CLERK_SECRET_KEY=sk_live_YOUR_PRODUCTION_SECRET"
echo "   - CLERK_ISSUER=https://clerk.adminer.online"
echo ""

echo "🗄️  2. DATABASE CONNECTION"
echo "   - DATABASE_URL=postgresql://username:password@your-neon-host/database"
echo "   - NEON_DATABASE_URL=postgresql://username:password@your-neon-host/database"
echo ""

echo "🤖 3. EXTERNAL SERVICE APIS"
echo "   - APIFY_TOKEN=your_production_apify_token"
echo "   - APIFY_ACTOR_ID=your_production_actor_id"
echo ""

echo "💳 4. PAYMENT SYSTEM (DODO)"
echo "   - DODO_SECRET_KEY=dodo_live_YOUR_PRODUCTION_SECRET_KEY"
echo "   - DODO_WEBHOOK_SECRET=whsec_your_production_webhook_secret"
echo "   - DODO_API_BASE=https://api.dodopayments.com"
echo "   - DODO_MODE=live"
echo ""

echo "🧠 5. AI SERVICES"
echo "   - OPENAI_API_KEY=sk-your-production-openai-key"
echo "   - GEMINI_API_KEY=your-production-gemini-key"
echo ""

echo "⚙️  6. INNGEST (BACKGROUND JOBS)"
echo "   - INNGEST_EVENT_KEY=your_production_event_key"
echo "   - INNGEST_SIGNING_KEY=your_production_signing_key"
echo ""

echo "🌐 7. APP CONFIGURATION"
echo "   - NEXT_PUBLIC_APP_URL=https://adminer.online"
echo "   - APP_BASE_URL=https://adminer.online"
echo "   - NODE_ENV=production"
echo ""

echo "🔒 8. SECURITY & WEBHOOKS"
echo "   - WEBHOOK_SECRET_APIFY=your_production_webhook_secret_apify"
echo "   - INTERNAL_ENDPOINTS_ENABLED=false"
echo ""

echo "📊 9. BILLING CONFIGURATION"
echo "   - BILLING_ENABLED=true"
echo "   - BILLING_AUTODOWNGRADE_ENABLED=true"
echo ""

echo "🚨 IMMEDIATE ACTION REQUIRED"
echo "============================"
echo ""
echo "1. Go to Vercel Dashboard → Your Project → Settings → Environment Variables"
echo "2. Add ALL the variables listed above"
echo "3. Set Environment to 'Production' for critical variables"
echo "4. Set Environment to 'All Environments' for shared variables"
echo ""

echo "🔍 VERIFICATION STEPS"
echo "====================="
echo ""
echo "After setting environment variables:"
echo "1. Redeploy your application"
echo "2. Test https://adminer.online"
echo "3. Verify dashboard loads without runtime errors"
echo "4. Test authentication flow"
echo "5. Verify database connectivity"
echo ""

echo "💡 TROUBLESHOOTING TIPS"
echo "======================="
echo ""
echo "- Check Vercel Function Logs for specific error messages"
echo "- Verify database connectivity from Vercel environment"
echo "- Ensure all API keys are valid and have correct permissions"
echo "- Test each service individually to isolate issues"
echo ""

echo "✅ SUCCESS CRITERIA"
echo "==================="
echo ""
echo "Production site should:"
echo "1. Load without '💥 A runtime error occurred' message"
echo "2. Display dashboard content properly"
echo "3. Allow user authentication"
echo "4. Process API requests successfully"
echo "5. Connect to database without errors"
echo ""

echo "🎯 NEXT STEPS"
echo "============="
echo ""
echo "1. Set up environment variables in Vercel dashboard"
echo "2. Redeploy application"
echo "3. Test production site functionality"
echo "4. Verify CI pipeline completes successfully"
echo "5. Monitor for any remaining runtime errors"
echo ""

echo "📞 SUPPORT"
echo "==========="
echo ""
echo "If you encounter issues:"
echo "1. Check Vercel function logs for error details"
echo "2. Verify environment variable values are correct"
echo "3. Test database connectivity manually"
echo "4. Check external service API key validity"
echo ""

echo "🚀 Ready to implement production environment variables!"
echo "======================================================" 