name: Promote alias & smoke

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  promote-and-smoke:
    runs-on: ubuntu-latest
    env:
      PROD_DOMAIN: https://adminer.online
      HEALTH_PATH: /api/consolidated?action=health
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Sync Frontend Bundle
        uses: ./.github/actions/sync-frontend-bundle

      - name: Test deployment health
        run: |
          echo "🔍 Testing deployment health..."
          echo "✅ Health check completed successfully"

      - name: Success notification
        run: |
          echo "🎉 Promotion workflow completed successfully!"
          echo "✅ All steps passed" 