name: Smoke Tests (Production)

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      base_url:
        description: "Base URL to test"
        default: "https://www.adminer.online"
        required: true
        type: string

concurrency:
  group: smoke-prod
  cancel-in-progress: false

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set BASE_URL
        run: |
          if [ -n "${{ github.event.inputs.base_url }}" ]; then
            echo "BASE_URL=${{ github.event.inputs.base_url }}" >> $GITHUB_ENV
          else
            echo "BASE_URL=https://www.adminer.online" >> $GITHUB_ENV
          fi

      # Optional small buffer so Vercel DNS/edge finishes propagating
      - name: Warm-up wait
        run: sleep 15

      - name: Run smoke tests
        env:
          BASE_URL: ${{ env.BASE_URL }}
          RETRIES: "30"       # up to ~2.5 minutes per endpoint with 5s sleep
          SLEEP_SECS: "5"
        run: |
          bash scripts/smoke.sh
