name: Smoke Tests (Production)

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      apex_url:
        description: "APEX URL to test"
        default: "https://adminer.online"
        required: true
        type: string
      www_url:
        description: "WWW URL to test"
        default: "https://www.adminer.online"
        required: true
        type: string

concurrency:
  group: smoke-prod
  cancel-in-progress: false

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      # Optional: if not provided, fall back to production apex/www.
      APEX_URL: ${{ secrets.PROD_URL }}
      WWW_URL: ${{ secrets.WWW_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure defaults for URLs when secrets not set
        run: |
          set -euo pipefail
          : "${APEX_URL:=https://adminer.online}"
          : "${WWW_URL:=https://www.adminer.online}"
          echo "APEX_URL=$APEX_URL" >> $GITHUB_ENV
          echo "WWW_URL=$WWW_URL" >> $GITHUB_ENV

      # Optional small buffer so Vercel DNS/edge finishes propagating
      - name: Warm-up wait
        run: sleep 15

      - name: Make smoke executable
        run: chmod +x scripts/smoke.sh

      - name: Run smoke tests
        run: bash scripts/smoke.sh
