name: Smoke (Prod)
on:
  workflow_dispatch:
  deployment_status:
    types: [success]
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Hit root (CSP present)
        run: |
          curl -sI https://www.adminer.online/ | grep -i "content-security-policy" || (echo "CSP header missing" && exit 1)
      - name: Quota endpoint
        run: |
          set -e
          body=$(curl -s "https://www.adminer.online/api/consolidated?action=quota/status")
          echo "$body"
          code=$(curl -s -o /dev/null -w "%{http_code}" "https://www.adminer.online/api/consolidated?action=quota/status")
          if [ "$code" != "200" ] && [ "$code" != "402" ]; then
            echo "Unexpected status: $code"; exit 1;
          fi
      - name: CSP report GET
        run: |
          curl -s "https://www.adminer.online/api/csp/report" | grep -q '"ok":true' || (echo "CSP report GET failed" && exit 1)
      - name: CSP report POST (json)
        run: |
          curl -s -X POST -H "Content-Type: application/json" \
            -d '{"document-uri":"gh-action"}' \
            "https://www.adminer.online/api/csp/report" | grep -q '"received":true' || exit 1
